### ISSUE TITLE
Una foto nueva.

### ISSUE THREAD

**Issue by ghost** [futurelabmx/FaceRecognition#1]
Vistos los últimos commits hechos por @LuisSustaita he visto que la foto usada no incluye a los participantes completos de Future Lab, mi sugerencia es re-hacer una foto donde se encuentren todas las personas que formen parte del equipo [**actualmente**].

Por ahora las personas que son parte del proyecto, identificables son:

- [x] Luis Sustaita
- [x] Ricardo Mirón
- [x] Rodolfo Ferro
- [x] Aldo Fernando
- [x] Francisco López Ortíz
- [x] Oliver A. López
- [x] Crístofer Nava
- [x] Miguel Aguirre
- [x] Polo A. Ruiz
- [x] Juan Manuel Pérez Rocha
- [x] Ernesto Ramírez de Sancristobal
- [x] Adolfo Ramírez de Sancristobal
- [x] Omar Jair Purata Funes

//Problablemente estén mas personas y no las haya incluido en ésta issue, posiblemente me olvidé de sus nombres o desconozco de su rol actual.

**Comment by LuisSustaita** [comment]
Los nombres que mencionas ya los tengo en una lista, podemos probar con la foto. Los nombres que faltan espero me los puedan facilitar para ir agregandolos :)
La foto la podemos tomar el día de la reunión regresando de vacaciones.
